spring:
  application:
    name: sue-eureka-server
server:
  port: 20000
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    ##将localhost指向本机（hosts文件）
    hostname: localhost