spring:
  application:
    name: sue-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GEKSS5289/sue-microservice-config.git
          force-pull: true
          # 将配置文件放到接入方服务名称对应的文件夹下面
          search-paths: '{application}'
        # 属性重载
        overrides:
          test: mytets
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
server:
  port: 20003