server:
  port: 10002

spring:
  datasource:                                           # 数据源的相关配置
#    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
#    password: 123456
#    username: root
     url: ${mysqldb.url}
     password: ${mysqldb.password}
     username: ${mysqldb.username}
  redis:
#    password: shushun
#    cluster:
#      nodes: 192.168.182.154:6379,192.168.182.155:6379,192.168.182.156:6379,192.168.182.157:6379,192.168.182.158:6379,192.168.182.159:6379
    #哨兵模式
#    password: shushun
#    sentinel:
#      master: sue-master
#      nodes: 192.168.182.150:26379,192.168.182.151:26379,192.168.182.152:26379
    #Redis 单机实例
#    host: 192.168.182.150
#    port: 6379
#    password: shushun
    host: 192.168.182.151
    port: 6379
    password: shushun


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

hystrix:
  command:
    default:
      fallback:
        enabled: true
      circuitBreaker:
        enabled: true
        #超过50%错误，那么开启熔断
        errorThresholdPercentage: 30
        #5个request之后才开始统计
        requestVolumeThreshhold: 5
        sleepWindowInMilliseconds: 10000
        #forceClosed,forceOpen 强制关闭/开启熔断开关
      execution:
        timeout:
          enable: true
        isolation:
          thread:
            interruptOnTimeout: true
            interruptOnFutureCancel: true
            timeoutInMilliseconds: 10000
      metrics:
        rollingState:
          timeInMilliseconds: 20000
          #numBuckets: 10
      #        rollingPercentile:
      #          #时间窗口统计
      #          timeInMilliseconds: 20000
      #          bucketSize: 300
      loginFail:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 3000